USE S16


--PROBLEM:
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--FIX:
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
INSERT INTO Echipe (Denumire, NrMembrii) VALUES('Silitorii', 12)
COMMIT TRAN

--DELETE FROM Echipe WHERE Denumire='Silitorii'