USE S16

--PROBLEM:
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--FIX:
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Echipe
WAITFOR DELAY '00:00:5'
SELECT * FROM Echipe
COMMIT TRAN
