USE LanguageCentre


--PROBLEM:
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--FIX:
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
UPDATE Languages SET name='RoRoEnglish' WHERE language_id=159
WAITFOR DELAY '00:00:3'
ROLLBACK TRAN
INSERT INTO Logs VALUES(GETDATE(), 'Rolled back Languages');

SELECT * FROM Logs