USE LanguageCentre


--PROBLEM:
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--FIX:
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
WAITFOR DELAY '00:00:3'
UPDATE Languages SET name='RoRoEnglish' WHERE language_id=159
INSERT INTO Logs VALUES(GETDATE(), 'Updated Languages');
COMMIT TRAN

SELECT * FROM Logs