USE LanguageCentre


--PROBLEM:
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--FIX:
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
WAITFOR DELAY '00:00:3'
INSERT INTO Languages VALUES('Chinese')
INSERT INTO Logs VALUES(GETDATE(), 'Insert New Language');
COMMIT TRAN

SELECT * FROM Logs
DELETE FROM Languages WHERE Name='Chinese'