USE LanguageCentre


--PROBLEM:
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
--FIX:
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
INSERT INTO Logs VALUES(GETDATE(), 'Get Languages');
SELECT * FROM Languages
WAITFOR DELAY '00:00:3'
INSERT INTO Logs VALUES(GETDATE(), 'Get Languages again');
SELECT * FROM Languages
COMMIT TRAN

SELECT * FROM Logs 
UPDATE Languages SET name='RoEnglish' WHERE language_id=159